Repository cartesi/machine-emulator, pull requests merged in 2023-10, with the labels that each got.

#142 fix: move constants to namespace to avoid colision
  src/test-utils.h
Labels: bug, enhancement

#147 Fix protoc compile errors on Ubuntu
  src/Makefile
Labels: bug

#143 Rollup enable by default
  .github/workflows/build.yml
  Dockerfile
  src/cartesi-machine-tests.lua
  src/cartesi-machine.lua
  src/machine-config.h
  src/machine.cpp
  src/tests/htif-rollup.lua
Labels: enhancement
