Repository cartesi/machine-emulator, pull requests merged in 2023-11, with the labels that each got.

#150 refactor: replace libb64 with custom base64 implementation
  Dockerfile
  README.md
  src/Makefile
  src/base64.cpp
  tools/template/control.template
Labels: refactor

#151 refactor: bundle nlohmann-json into third-party
  Dockerfile
  README.md
  src/Makefile
  src/json-util.h
  src/jsonrpc-remote-machine.cpp
  src/jsonrpc-virtual-machine.cpp
  src/test-machine-c-api.cpp
  third-party/dependencies
  third-party/shasumfile
Labels: refactor

#158 fix: missing climits include in json-util.cpp
  src/json-util.cpp
Labels: bug

#160 Add conventional commits check workflow
  .github/workflows/commits.yml
Labels: enhancement

#163 fix: make append options work when empty
  src/cartesi-machine.lua
Labels: bug
