Repository cartesi/machine-emulator, pull requests merged in 2023-08, with the labels that each got.

#115 fix: Use Solidity style
  src/uarch-interpret.cpp
  src/uarch-step.cpp
  src/uarch-step.h
Labels: bug

#117 fix: fix server running check in test script
  src/tests/test-grpc-server.sh
  src/tests/test-jsonrpc-server.sh
Labels: bug

#116 ci: Add all proofs to uarch-riscv-tests-json-logs
  .github/workflows/build.yml
Labels: enhancement

#118 Release 0.15.0
  CHANGELOG.md
  src/Makefile
Labels: enhancement

#119 fix: Upload of json logs to the github release
  .github/workflows/build.yml
Labels: bug

#121 fix: add Bellard's copyright notice back to necessary files
  src/soft-float.h
  src/translate-virtual-address.h
Labels: documentation

#122 Fixed the list of files on the strip and patch installation step
  CHANGELOG.md
  Makefile
Labels: bug

#123 Release 0.15.1
  CHANGELOG.md
  src/Makefile
Labels: documentation

#127 doc: Update CHANGELOG.md
  CHANGELOG.md
  src/Makefile
Labels: documentation
