Repository cartesi/machine-emulator, pull requests merged in 2024-04, with the labels that each got.

#215 Add new docker like command line options
  src/cartesi-machine.lua
Labels: enhancement

#224 Optimize fdiv and fsqrt instructions for uarch
  src/soft-float.h
Labels: enhancement, optimization

#225 ci: speed up uarch testing in CI
  .github/workflows/build.yml
Labels: enhancement

#220 feat: add C API to translate virtual address
  src/clua-i-virtual-machine.cpp
  src/i-virtual-machine.h
  src/jsonrpc-discover.json
  src/jsonrpc-remote-machine.cpp
  src/jsonrpc-virtual-machine.cpp
  src/jsonrpc-virtual-machine.h
  src/machine-c-api.cpp
  src/machine-c-api.h
  src/machine.cpp
  src/machine.h
  src/virtual-machine.cpp
  src/virtual-machine.h
  tests/misc/test-machine-c-api.cpp
Labels: enhancement

#228 fix: compile error with slirp=no on Linux
  src/virtio-net.cpp
Labels: bug

#231 refactor: remove unmaintained and broken benchmarks script
  tools/benchmarks/run-benchmarks.lua
Labels: enhancement

#230 Simplify solidity step generation
  src/uarch-step.cpp
  tests/lua/uarch-riscv-tests.lua
Labels: enhancement

#234 Fix JSONRPC connection issues on edge cases
  src/jsonrpc-remote-machine.cpp
  src/jsonrpc-virtual-machine.cpp
Labels: bug

#235 fix: allow saving snapshots on first machine yield
  src/virtual-machine.cpp
Labels: enhancement
