Repository cartesi/machine-emulator, pull requests merged in 2024-03, with the labels that each got.

#194 Fix Homebrew libslirp options
  src/Makefile
  tests/misc/Makefile
Labels: bug

#197 Fix trailing comma in jsonrpc-discover.json
  src/jsonrpc-discover.json
Labels: bug

#196 Use Sv39 address spacing by default to support nodejs and improve performance
  src/cartesi-machine.lua
Labels: enhancement

#201 feat: introduce the `--user` command line option
  src/cartesi-machine.lua
Labels: enhancement, refactor

#200 feat: Include uarch-reset log in catalog.json
  tests/Makefile
  tests/lua/uarch-riscv-tests.lua
  tests/scripts/collect-uarch-test-logs.sh
Labels: enhancement

#211 fix: Correct reset_uarch documentation
  src/machine-c-api.h
  src/machine.h
Labels: documentation

#212 fix: compile amd64 debian package in release mode on releases
  .github/workflows/build.yml
Labels: bug

#205 feat: add new runtime option to skip storing machine root hash
  src/cartesi-machine.lua
  src/clua-machine-util.cpp
  src/json-util.cpp
  src/jsonrpc-discover.json
  src/machine-c-api.cpp
  src/machine-c-api.h
  src/machine-runtime-config.h
  src/machine.cpp
Labels: enhancement
